cyberark/conjur-api-ruby

- CHANGELOG.md
- conjur-api.gemspec
- lib/conjur-api/version.rb
- lib/conjur/api/groups.rb
- lib/conjur/group.rb
- spec/api/groups_spec.rb
- spec/lib/group_spec.rb
[#87827704]
Please verify the version number before merging.
> GID manipulation support

- lib/conjur/acts_as_user.rb
- lib/conjur/api/authn.rb
- spec/api/users_spec.rb
* Add #rotate_api_key method to ActsAsUser
* Update Conjur::API.rotate_api_key
* Spec it
> Support rotating another user's API key.

- CHANGELOG.md
- lib/conjur/host_factory_token.rb
> Show CIDR restrictions when displaying results of creating a hostfactory token

- CHANGELOG.md
- features/bootstrap.feature
- lib/conjur-api/version.rb
- lib/conjur/bootstrap.rb
https://jenkins.conjur.net/job/api-ruby/409/
> Add expiration role

- features/bootstrap.feature
- lib/conjur/bootstrap.rb
This PR changes bootstrap to grant security_admin update on the pubkeys service.
> Fix pubkeys permissions [CON-3049]

- lib/conjur/api/ldapsync.rb
- lib/conjur/ldap_sync_job.rb
- spec/api/ldapsync_spec.rb
This PR adds support for listing and deleting ldap sync jobs, and for retrieving their output.
> Manage LDAP Sync Jobs [CON-3231]

- CHANGELOG.md
- lib/conjur-api/version.rb
- lib/conjur/api/ldapsync.rb
- spec/api/ldapsync_spec.rb
get rid of API#ldap_sync_jobs and API#ldap_sync_now
> CON-3568 add API#ldap_sync_policy, use the new ldap-sync entrypoint

- CHANGELOG.md
- Gemfile
- conjur-api.gemspec
- jenkins.sh
- lib/conjur-api/version.rb
- lib/conjur/configuration.rb
- spec/lib/configuration_spec.rb
Pin rake to fix the build, test against 4.9.
> CON-3720 Ensure cert file is readable before trying to use it

- .dockerignore
- Dockerfile
- Dockerfile.test
- Jenkinsfile
- Rakefile
- ci/setup-account.sh
- ci/test.sh
- features/host_factory_token.feature
- features/permitted_roles.feature
- jenkins.sh
- lib/conjur/host_factory_token.rb
- test.sh
Fixes #97.
To review, verify that the new pipeline build is green.
Note that I marked two cukes `@wip`. These will be addressed in a follow on story.
> Switch to pipeline build

- CHANGELOG.md
- lib/conjur-api/version.rb
Changelog entry for previous change.
@apotterri
> Changelog Addition

- Rakefile
- conjur-api.gemspec
Closes https://github.com/cyberark/conjur-api-ruby/issues/121.
> Fix broken master build

- README.md
- dev/Dockerfile.dev
- dev/docker-compose.yml
- dev/start
- dev/stop
- features/new_api.feature
* Fixes failing tests which occurred when we limited a resource's ability to see all other resources in Conjur.
*  Adds development scripts to make it easier to run and debug. These scripts are V5 only due to time constraints.
No
[CONJ-5100](https://ca-il-jira.il.cyber-ark.com:8443/browse/CONJ-5100)
Fixes for broken features are in: `features/new_api.feature`
Feel free to start and run tests in the container.  
https://jenkins.conjur.net/job/cyberark--conjur-api-ruby/job/resolve-broken-cucumber-features/
No, but I don't think we should change it.  There is no new functionality.
> Fixed failing tests 

- Gemfile
- Jenkinsfile
- docker-compose.yml
- features/support/env.rb
- features_v4/support/env.rb
- spec/spec_helper.rb
This repo now can output Jenkins-consumable reports about code coverage
of the tests.
> Add code coverage metrics to build

- conjur-api.gemspec
> Bump rake version to 12.3.3

- test.sh
Update to provide GIT_COMMIT and GIT_BRANCH in reporting to CodeClimate so that the coverage results are properly collected and correlated inside CodeClimate.
> Update to provide GIT_BRANCH/GIT_COMMIT in CodeClimate submission

- CHANGELOG.md
- lib/conjur-api/version.rb
Bump version to v5.3.5
Connected to -
> Bump version to v5.3.5

- LICENSE
- conjur-api.gemspec
- lib/conjur-api/version.rb
Update authors Gemspec + Copyright dates
Connected to -
> Project cleanup

- Dockerfile
- Jenkinsfile
- ci/codeclimate.dockerfile
- ci/submit-coverage
- conjur-api.gemspec
- docker-compose.yml
- features/support/env.rb
- spec/spec_helper.rb
- test.sh
- _What's changed? Why were these changes made?_
These changes fixed the Jenkins build process and allowed multiple versions of Ruby to be tested. 
- _How should the reviewer approach this PR, especially if manual tests are required?_
To make sure the changes are in line with the established best practices. 
- _Are there relevant screenshots you can add to the PR description?_
No
Connected to # 174
> Test against multiple Ruby versions

- Gemfile
- Jenkinsfile
- test.sh
- _What's changed? Why were these changes made?_
Added test for Ruby version 2.7
- _How should the reviewer approach this PR, especially if manual tests are required?_
Make sure the formatting is good.
- _Are there relevant screenshots you can add to the PR description?_
No
Connected to #316
> 316 --  Add Ruby 2.7 to tests

- features/permitted.feature
Enlarge test coverage of permission check area
Add more tests calling permissions check rest api.
changes, or
> Test more complex names as role parameter in permitted check

- Jenkinsfile
Fixes git clean call to fully support new release process.  Successful release using these changes can be seen at https://jenkins.conjur.net/job/cyberark--conjur-api-ruby/job/automated-release-process/14/
> Change git cleanup call

- dev/start
- test.sh
Add automatic generation of `VERSION` file during local development
> Update to support auto-local VERSION files

- CHANGELOG.md
This is a step of the automated release process. 
Any CHANGELOG entries from now until V5.3.8 release should be under this section.
Added V5.3.8 CHANGELOG entry.
changes, or
> Add changelog entry for next V5.3.8

- CHANGELOG.md
- Jenkinsfile
Fix git clean step of release publishing 
- Fix git clean step of release publishing 
Release builds successfully create pre-release
changes, or
> Fixup git call to avoid safe.directory need

- CHANGELOG.md
Bump version to 5.4.0
changes, or
> Bump version to 5.4.0

- .gitignore
- dev/Dockerfile.dev
Upgrade `Dockerfile.dev` to Ruby 3 from 2.7
- Upgrade `Dockerfile.dev` to Ruby 3
- Copy generated `VERSION` file into `Dockerfile.dev` before bundling Gems
- Add generated `VERSION` file to `.gitignore`
CNJR-65
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
changes, or
> Upgrade Dockerfile.dev to Ruby 3

- CHANGELOG.md
*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*
*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*
- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_
Resolves #[relevant GitHub issue(s), e.g. 76]
CyberArk internal issue ID: [insert issue ID]
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
changes, or
> Add empty v5.4.2 Changelog entry
