cyberark/conjur-api-ruby

lib/conjur/standard_methods.rb
The problem here was that when given an id with characters like `'/'`, fully_escape would be called on an id like `'pubkeys-1.0/public-keys'`, to give` 'pubkeys-1.0%2Fpublic-keys'`.  This would then be passed to a `standard_show` method like `layer` or `group`, which would `fully_escape` the id again, replacing the `'%'` character with `'%25'` before putting it in the objects's `url`.  For the id above, you'd end up with `'pubkeys-1.0%252Fpublic-keys'`.  The double escape would result in bogus behavior like
```ruby
api.layers[0].exists? 
```
when `api.layers[0].id` happens to contain an escaped character like `'/'`.
=> don't escape ids twice when listing records

CHANGELOG.md, lib/conjur-api/version.rb, lib/conjur/configuration.rb, spec/lib/configuration_spec.rb
Now accepts `ssl_certificate` (`"CONJUR_SSL_CERTIFICATE"`) option containing a certificate as a string, and adds a `apply_cert_config!` method to `Conjur::Configuration` to handle the trickiness of trusting the certs in `ssl_certificate` and `cert_file`.  No breaking changes.
=> Feature: Cert config improvements

CHANGELOG.md, lib/conjur-api/version.rb, lib/conjur/api/resources.rb, lib/conjur/base.rb, spec/lib/api_spec.rb
It was only present in docstrings and specs.
=> Rename sudo to elevate

lib/conjur/api.rb
Note that this change is incompatible with @dividedmind 's PR https://github.com/conjurinc/api-ruby/pull/49
=> [#104210460] fix --follow for conjur audit subcommands

lib/conjur/cert_utils.rb, lib/conjur/configuration.rb, spec/lib/cert_utils_spec.rb, spec/lib/configuration_spec.rb
This comes up eg. when running a Conjur script -- two certs get saved
in the context file, but only one ends up getting loaded, which results
in verification error.
=> Allow Configuration to parse several certs in a string

lib/conjur/escape.rb, spec/lib/api_spec.rb
Our services don't handle `+` signs in URL path components correctly.  This breaks (among other things) ldap-sync with default AD groups (e.g. `Domain Controllers`) that contain spaces in their common names.
This PR changes the `Conjur::Escape#fully_escape` method to use a slightly modified version of `CGI.escape` to encode spaces with `%20` instead of `+`.
The original `CGI.escape` method can be seen here: https://github.com/ruby/ruby/blob/trunk/lib/cgi/util.rb#L8.
=> Escape spaces in URLs with `%20` instead of `+`

CHANGELOG.md, conjur-api.gemspec, lib/conjur/base.rb, lib/conjur/error.rb, lib/conjur/user.rb, spec/lib/api_spec.rb
Also, in that case, use the (a bit) stale token for as long
as it's still valid.
=> Don't try to refresh authentication token if not possible

CHANGELOG.md, lib/conjur-api/version.rb, lib/conjur/base.rb
This will workaround the 404 core bug for long-running operations (when the token is used right around the 5 minute mark) on older appliances.
That one minute shouldn't make that much of a difference in performance.
=> Set TOKEN_STALE to 4 minutes

CHANGELOG.md, Gemfile, jenkins.sh, lib/conjur-api/version.rb, lib/conjur/base.rb, spec/lib/api_spec.rb
When `with_privilege`, `with_audit_roles`, and `with_audit_resources` create a new API instance, make sure that new instance knows when it needs to refresh its token.
=> CON-3025 make sure token refresh works for long-lived API instances

CHANGELOG.md, lib/conjur-api/version.rb, lib/conjur/api/ldapsync.rb
Note that this functionality is currently tested by cukes in https://github.com/conjurinc/ldap-sync
=> CON-3593 include log events in hash returned by ldap_sync_policy

conjur-api.gemspec, lib/conjur/base.rb, spec/lib/api_spec.rb
This avoids reading the token repeatedly even if it wasn't changed, and allows changing the token before it expires (eg. to switch identities).
Also get the mtime from the opened file instead of directory, so that it's accurate even if the file was replaced concurrently.
=> Refresh token always when the token file mtime changes

CHANGELOG.md, Dockerfile, Jenkinsfile, ci/setup-account.sh, ci/test.sh, ci/wait_for_server.sh, dev/docker-compose.yml, dev/start.sh, docker-compose.yml, jenkins.sh, test.sh
Build is green here: https://jenkins.conjur.net/view/Conjur%205.x/job/cyberark--conjur-api-ruby/job/rename-possum-references/
I think we should create a new issue to get this released as 5.0.0. Closes #112.
=> Rename possum references

Jenkinsfile
I just need a visual check. I'll take care of any releasebot issues if they come up. Once we have this first `pre` pushing from master we can refine this more.
Take note of `stage('Publish to RubyGems?')` in this PR - instead of relying on the buggy and intrusive jenkins promotion plugins we can use `input` like this for promotions. It's a little verbose, but maybe we could wrap this into a nice simple pipeline library function later on?
=> Adds a promotion step for pushing conjur-api-ruby to RubyGems

Jenkinsfile, publish.sh
Uses the image created in this PR: https://github.com/conjurinc/publish-rubygem/pull/1 to build and publish a gem as part of a locally managed `publish.sh` step.
`publish.sh` has the heavy lifting.
This PR is hard to manually test due to the fact that it requires access to the API key. 
As I understand Jenkin's Pipelines, this approach enables a developer to run more steps locally (assuming API credential access), which is desired.
Fixes [#188](https://github.com/cyberark/conjur/issues/188)
https://jenkins.conjur.net/job/cyberark--conjur-api-ruby/job/pipeline-publishing/
Please note this publish step only runs against the master branch.
@dustinmm80
=> Leverage `publish-rubygems` image to build and publish gem

features_v4/resource_fields.feature, features_v4/support/policy.yml, features_v4/variable_fields.feature, features_v4/variable_value.feature, lib/conjur/api/router/v4.rb, lib/conjur/api/router/v5.rb, lib/conjur/group.rb, lib/conjur/has_attributes.rb, lib/conjur/user.rb, lib/conjur/variable.rb
In v4, objects such as Variable, User and Group have their own database table, and some fields (kind, mime_type, uidnumber, gidnumber) are stored on these tables, and can only be accessed through a URL route like `GET /<pluralized-object-kind>/<object-identifier>`
In v5, all this extended data is stored on annotations. 
This pull request add special JSON fetching and parsing logic to properly handle these attributes which differ between v4 and v5.
**Note** The CHANGELOG and VERSION are not updated yet, because v5.1.0 has not yet been released to Rubygems.
Build results : https://jenkins.conjur.net/job/cyberark--conjur-api-ruby/job/v4_field_compatibility/
=> Add special handling for some v4 / v5 object field differences

CHANGELOG.md, features/members.feature, lib/conjur/api/router/v5.rb
For CONJ-5074
This PR updates the Conjur Ruby API to use the `?members` endpoint in Conjur Role API to return the members and make them searchable and pageable.
In version 5, before the `?members` route was added, these requests were being handled by the role endpoint, which contains a `members` property. With this endpoint, the `parse_members` method needs to look at the JSON root, rather than the prior property path.
https://jenkins.conjur.net/job/cyberark--conjur-api-ruby/job/search_role_members/
Yes
=> Update API client to use updated Role members endpoint for search

CHANGELOG.md, lib/conjur/api/router/v5.rb, lib/conjur/id.rb, spec/uri_escape_spec.rb
This PR adds escaping to the resource name for two places in the API that cause the V5 UI to break.
https://github.com/conjurinc/conjur-ui/issues/171
I would appreciate any feedback on if there is a better way to use the `escape.rb` methods in `id.rb`.
https://jenkins.conjur.net/job/cyberark--conjur-api-ruby/job/spaces_in_params/
Yes
=> URL parameters with spaces are properly escaped in the API

test.sh
test.sh used to do `docker-compose pull` which unconditionally pulls
fresh images. Usually it's a waste of bandwidth and time:
`docker-compose build` already pulls any missing images, whereas
updating on every run means cache is busted and many images potentially
need to be rebuilt. It also prevents offline usage. If anything relies
on a recent image it should be explicitly pulled in.
=> Utils: Do not force pull in test.sh

CHANGELOG.md, lib/conjur/api/router/v5.rb, lib/conjur/id.rb, spec/uri_escape_spec.rb
This PR adds additional tests for URL escaping to standardize on how path parameters should be escaped. Presently `fully_escape` and `path_escape` are used without a clear reason for selecting one versus the other.
I've updated many of the router methods to use `fully_escape` more consistently, rather than use path_escape, to account for the possibility of forward slashes in resource IDs.
This is related to https://github.com/conjurinc/conjur-ui/issues/210
https://jenkins.conjur.net/job/cyberark--conjur-api-ruby/job/uri_escaping/
=> Make resource ID escaping more consistent and add additional tests

lib/conjur/base_object.rb, spec/base_object_spec.rb
Added a custom inspect method to the `BaseObject` class that simply prints the class name and the id, instead of the less readability version from `Object`.  As this is a superclass, all subclasses will now inherit this version of the inspect method.
Example:
```ruby
[4] pry(main)> a.inspect
=> "<Conjur::User id='admin:user:admin'>"
```
=> Provide improved inspect method

.codeclimate.yml, .gitignore, Jenkinsfile, ci/codeclimate.dockerfile, test.sh
This commit adds a Docker container to handle publishing coverage reports to Code Climate. A docker container based install was chosen to allow a developer to run the CC publish step locally.
=> Publish coverage to Code Climate

.rubocop_settings.yml, conjur-api.gemspec
This PR removes `parse-changelog.sh` from the Gemspec executables.
Connected to cyberark/conjur-cli#261 
`parse-changelog.sh` is a development dependency of the API, and when other Gems also include this script, it causes an error when installed together.
For example, installing both `conjur-api` and `conjur-cli` leads to:
```
$ gem install ./conjur-cli-6.2.1.gem
conjur-cli's executable "parse-changelog.sh" conflicts with conjur-api
```
=> Remove parse-changelog.sh from gem executables

CONTRIBUTING.md, Jenkinsfile
Changes the publish to RubyGems process to publish on push to master with a tagged(v*) release. Ex) `v5.3.2`
More notes in the issue.
Connected to https://github.com/cyberark/conjur-api-ruby/issues/173
- [ x ] This PR does not include user-facing changes and doesn't require a CHANGELOG update
- [ x ] The changes in this PR do not require tests
- [ x ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
=> Publish to RubyGems on tagged version

CHANGELOG.md, features/host.feature, features/step_definitions/api_steps.rb, features/step_definitions/policy_steps.rb, features/user.feature, lib/conjur/acts_as_user.rb, lib/conjur/api/resources.rb, lib/conjur/api/router/v5.rb, lib/conjur/base.rb, lib/conjur/base_object.rb, spec/api_spec.rb, spec/base_object_spec.rb
This change modifies the API to reject attempts at using the
`resource(<own_id>).rotate_api_key` for changing your own API key
as `Conjur::API.rotate_api_key` should be used instead for that.
Additional test cases are now included to cover all logic paths and
proper extraction of the username from a JWT to enable this
functionality.
Connected to #181
=> Add explicit failure for `resource(<own_id>).rotate_api_key`

CHANGELOG.md, lib/conjur-api/version.rb
This change prepares the API for a release of v5.3.4 with fixed to key
rotation logic.
Connected to #182
=> Bump version to v5.3.4

Gemfile, Jenkinsfile, features/support/env.rb, features_v4/support/env.rb, spec/spec_helper.rb
- _What's changed? Why were these changes made?_
Cobertura was deemed unnecessary by the infrastructure team, and though originally left in, it changed its line coverage rating on files that weren't altered. It was decided to remove the line publishing the report, and instead use only ccCoverage. 
- _How should the reviewer approach this PR, especially if manual tests are required?_
Make sure the Jenkinsfile is in align with the teams' standards. 
- _Are there relevant screenshots you can add to the PR description?_
No
Connected to #174
=> Remove cobertura from the jenkinsfile

CHANGELOG.md, lib/conjur-api/version.rb
Bump conjur-api-ruby version to 5.3.6.
Modified changelog and version.rb file.
CyberArk internal issue link: [ONYX-14614](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14614)
Version 5.3.6 is staged for tagging.
changes, or
=> Bump version to 5.3.6

CHANGELOG.md, conjur-api.gemspec
Addressable dependency changed from (~> 2.8.0) to (~2.0) to allow compatability with other gems in conjur.
Change dependency in conjur-api.gemspec
CyberArk internal issue link: [ONYX-14705](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14705)
Same addressable version (2.8.0) is used within conjur-api-ruby.
Dependency changed to (~> 2.0).
Jenkins CI tests are green.
changes, or
=> Addressable gem dependency update

CHANGELOG.md, Dockerfile, Jenkinsfile, conjur-api.gemspec, lib/conjur-api/version.rb
Update to use automated release process, providing continues delivery of releases appropriately marked as pre-release and provide a lightweight route for promoting a given pre-release to customer release.
When a build is triggered by a dependency or from a merge to master, the project will be built, a prerelease version published to rubygems, and a github pre-release release created or updated based on the changelog.  Builds will indicate the type of build it is (BUILD, RELEASE, PROMOTE or SKIP) in the description and the associated versions used. The version used is determined on the latest version in the changelog, so if a version (say 1.2.3) has been promoted, and a merge occurs without a new version being added to the changelog, the build will fail on the main branch.  To promote a …
=> ONYX-14702: Update to use automated release process

Jenkinsfile, publish.sh
This moves away from the publish-rubygem container to use the
release-tools provided publish-rubygem.  This allows the gem file
to be archived along with the release rather than just on rubygems.org
Release builds will fail until conjurinc/release-tools#17 has been merged.
=> Update to use release-tools publish-rubygem

.rubocop_settings.yml, CHANGELOG.md, CONTRIBUTING.md, Jenkinsfile, bin/parse-changelog.sh, dev/Dockerfile.dev
dev/Dockerfile.dev in conjur-api-ruby uses the ruby:2.5 base image. This image includes a number of known vulnerabilities. Update this to a later version (preferably one that matches our upgraded Ruby version everywhere else).
- Remove support for Ruby versions below 2.7, which are [end of life](https://endoflife.date/ruby).
CyberArk internal issue link: [ONYX-16435](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-16435)
changes, or
=> Remove support for Ruby <2.7

features/authn.feature, features/step_definitions/api_steps.rb, lib/conjur/api/authn.rb, spec/api/host_factories_spec.rb
NOTE: The changes from this PR are also included in [PR 213](https://github.com/cyberark/conjur-api-ruby/pull/213) along with additional functionality to make POSt requests to the authenticator endpoint.
Currently, Conjur's Ruby API withholds detailed response information from users on most of its functions, only returning choice details after parsing a RestClient::Response object. This includes [functions responsible for submitting OIDC authentication requests](https://github.com/cyberark/conjur-api-ruby/blob/main/lib/conjur/api/authn.rb#L69).
Users of the Conjur Ruby API need a path for submitting OIDC authentication requests, and receiving in response the raw RestClient::Response object. Specifically, this would give the Ruby API user access to Conjur's response headers.
* Turn …
=> Allow raw response on OIDC authentication request

CHANGELOG.md, Jenkinsfile
Test against only Ruby 3.0+
- Remove Jenkins stage testing against Ruby 2.7
- Include Jenkins stage testing against Ruby 3.1
- Include Jenkins stage testing against Ruby 3.2
CNJR-1433
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
changes, or
=> Remove Ruby v2.7 tests, include tests for 3.1 and 3.2

ci/oauth/keycloak/fetch_certificate, features/step_definitions/policy_steps.rb
Fix failing Jenkins build. Logs:
```
12:59:24  Feature: List and manage authenticators
...
12:59:25    Scenario: Get a list of OIDC providers                   # features/authenticators.feature:36
12:59:25      When I run the code:                                   # features/step_definitions/api_steps.rb:1
12:59:25        """
12:59:25        $conjur.authentication_providers("authn-oidc")
12:59:25        """
12:59:25      Then the providers list contains service id "keycloak" # features/step_definitions/result_steps.rb:9
12:59:25        expected [] to include "keycloak" (RSpec::Expectations::ExpectationNotMetError)
12:59:25        ./features/step_definitions/result_steps.rb:10:in `/^the providers list contains service id "([^"]+)"$/'
12:59:25        features/authenticators.feature:41:in …
```
=> Use new AuthnOIDC ca-cert variable in test
